#!/usr/bin/env sh
#                 __          _
#    __  ______ _/ /_  ____ _(_)
#   / / / / __ `/ __ \/ __ `/ /
#  / /_/ / /_/ / /_/ / /_/ / /
#  \__, /\__,_/_.___/\__,_/_/
# /____/
#
#  ▓▓▓▓▓▓▓▓▓▓
# ░▓ author ▓ ROGUE(X3) <rowanfeely.github.io>
# ░▓   code ▓ https://github.com/RowanFeely/dotfiles
# ░▓▓▓▓▓▓▓▓▓▓
# ░░░░░░░░░░

# global settings
yabai -m config mouse_follows_focus            off
yabai -m config focus_follows_mouse            autoraise
yabai -m config window_placement               second_child
yabai -m config window_topmost                 on
yabai -m config window_opacity_duration        0.2
yabai -m config window_opacity                 off
# yabai -m config active_window_opacity          1.0
# yabai -m config normal_window_opacity          0.9
yabai -m config window_shadow                  off
# yabai -m config insert_feedback_color        0xaad75f5f
yabai -m config active_window_border_color     0xff272822
yabai -m config normal_window_border_color     0xff222222
yabai -m config insert_feedback_color          0xffc2c2b0
yabai -m config window_border_width            4
yabai -m config window_border                  off
yabai -m config split_ratio                    0.50
yabai -m config auto_balance                   off
yabai -m config mouse_modifier                 ctrl
yabai -m config mouse_action1                  move
yabai -m config mouse_action2                  resize

# general space settings
yabai -m config layout                         bsp
yabai -m config top_padding                    50
yabai -m config bottom_padding                 13
yabai -m config left_padding                   18
yabai -m config right_padding                  18
yabai -m config window_gap                     15

# unmanaged windows
yabai -m rule --add app="^System Preferences$" manage=off
yabai -m rule --add app="^VLC$" manage=off
yabai -m rule --add app="^Finder$" manage=off
yabai -m rule --add app="^Calculator$" manage=off
yabai -m rule --add app="^The\ Unarchiver$" manage=off
yabai -m rule --add app="^CleanMyMac\ X$" manage=off
yabai -m rule --add app="^GIMP-2.10$" manage=off
yabai -m rule --add app="^Spotify$" manage=off
yabai -m rule --add app="^Music$" manage=off
yabai -m rule --add app="^Mupen64Plus OpenGL Video Plugin by Rice v2.5.0$" manage=off
yabai -m rule --add app="^mupen64plus$" manage=off
yabai -m rule --add app="^Caprine$" manage=off

yabai -m space 1 --label "DIR"
yabai -m space 2 --label "WEB"
yabai -m space 3 --label "DEV"
yabai -m space 4 --label "SOCIAL"
yabai -m space 5 --label "MUSIC"

# Files
yabai -m rule --add app="^Finder$"                      space=2
yabai -m rule --add app="^EasyFind$"                    space=2
# Dev
yabai -m rule --add app="^Alacritty$"                   space=4
yabai -m rule --add app="^Code$"                        space=4
yabai -m rule --add app="^Android Studio$"              space=4
yabai -m rule --add app="^iA Writer$"                   space=4
# Browsing
yabai -m rule --add app="^Firefox Developer Edition$"   space=3
yabai -m rule --add app="^Firefox$"                     space=3
yabai -m rule --add app="^Google Chrome$"               space=3
yabai -m rule --add app="^Tor Browser$"                 space=3
# MUSIC
yabai -m rule --add app="^Spotify$"                     space=1
yabai -m rule --add app="^Music$"                     space=1
# COMMS
yabai -m rule --add app="^Caprine$"                     space=5
yabai -m rule --add app="^Messages$"                    space=5
# ORGANIZER
yabai -m rule --add app="^Trello$"                      space=6
yabai -m rule --add app="^Things$"                      space=6

# VM
yabai -m rule --add app="^VirtualBox$"                  space=7
yabai -m rule --add app="^VirtualBoxVM$"                space=7
yabai -m rule --add app="^VirtualBox VM$"                space=7

# send menubar notification
/usr/local/bin/notify-send -m " yabairc"
